### ISSUE TITLE
lib folder missing

### ISSUE THREAD

**Issue by WORMSS** [gabrielperales/prettier-init#10]
Hello, I ran the usual install 

```shell
npm install -g prettier-init

+ prettier-init@1.2.0
added 40 packages from 38 contributors in 5.589s
```

But I was greeted with 
```
$ prettier-init
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '../lib/cli'
```
After a little investigating I found this in the `package.json`
```json
"files": [
  "bin"
]
```
So it seems it's not adding `lib` folder.

### Solution
Once I downloaded the repo and manually copied the lib file into the global directory relative to the `/bin/` folder, everything seems to be working.

**Comment by gabrielperales** [comment]
Hey @WORMSS, thank you for helping me to fix this issue. For some reason I was not having this problem when I tried the code with `npm link`. I just have updated the package in NPM and now it should work.

**Comment by gabrielperales** [comment]
BTW, I'm not maintaining too much this library, but is nice to see that is being helpful for others, so if you know any other features that you would like to have, please let me know and also feel free to make PRs.

**Comment by WORMSS** [comment]
Confirmed it works now. Thank you.
