### ISSUE TITLE
Showing default values next to checkboxes

### ISSUE THREAD

**Issue by YassineGherbi** [gabrielperales/prettier-init#5]
First of all, I want to thank you for this handy library!

When I was using it I thought that it might be intuitive to show the default values when letting the user decide which properties they want in the generated `.prettierrc` next to the checkboxes.

If this is to much work for you I'm willing to help (with a PR). Just let me know if this is something that's in the scope of this project

**Comment by gabrielperales** [comment]
@YassineGherbi let me check if I have time to implement that, otherwise if you want to PR it, just go for it.
